#!/bin/bash

if [ "$#" -ne 2 ]; then
  echo "Usage: $0 [old driver] [new driver]" >&2
  exit 99
fi

OLD_DRIVER="$1"
NEW_DRIVER="$2"

modprobe "$NEW_DRIVER" 2>/dev/null

ints=$(/sbin/dpdk-devbind --status | grep -v "Active" | grep "drv=$OLD_DRIVER" | grep "unused=$NEW_DRIVER" | awk '{print $1}')

for int in $ints; do
  /sbin/dpdk-devbind --bind=$NEW_DRIVER $int
done
