---
version: 2
dps:
    at-x930:
        dp_id: 0xECCD6DF7D4AA
        hardware: 'Allied-Telesis'
        interfaces:
            port1:
                number: 1
                native_vlan: 10
            port2:
                number: 2
                native_vlan: 10
            port5:
                number: 5
                native_vlan: 10
            port6:
                number: 6
                native_vlan: 10
    ovs-nznog:
        dp_id: 0x0000a0369f5c3fb8
        hardware: 'Open vSwitch'
        interfaces:
            port1:
                number: 1
                native_vlan: 10
            port2:
                number: 2
                native_vlan: 10
            port3:
                number: 3
                native_vlan: 10
            port4:
                number: 4
                native_vlan: 10
            port5:
                number: 5
                native_vlan: 10
            port6:
                number: 6
                native_vlan: 10
            port7:
                number: 7
                native_vlan: 10
            port8:
                number: 8
                native_vlan: 10
            port9:
                number: 9
                native_vlan: 10
            port10:
                number: 10
                native_vlan: 10
            port11:
                number: 11
                native_vlan: 10
            port12:
                number: 12
                native_vlan: 10
    ovs-control:
        dp_id: 0x0000a0369f5d0a2c
        hardware: 'Open vSwitch'
        interfaces:
            port1:
                number: 1
                native_vlan: 99
            port2:
                number: 2
                native_vlan: 99
            port3:
                number: 3
                native_vlan: 99
            port4:
                number: 4
                native_vlan: 99
            port5:
                number: 5
                description: "faucet container"
                native_vlan: 99
            port6:
                number: 6
                description: "gauge container"
                native_vlan: 99
            port7:
                number: 7
                description: "host container"
                native_vlan: 99

vlans:
    10:
        name: 'nznog default vlan'
    99:
        name: 'control traffic'
